# Generated by Django 5.1 on 2024-10-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCrawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='img_src',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='transport',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
