# Generated by Django 5.1.2 on 2024-10-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCrawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtimeinfo',
            name='full_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
