# Generated by Django 5.1.1 on 2024-09-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('joining_on', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('screen', models.CharField(max_length=20, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('img_src', models.CharField(max_length=100, null=True)),
                ('info', models.CharField(max_length=100, null=True)),
                ('update_time', models.DateField(max_length=100, null=True)),
            ],
        ),
    ]
