# Generated by Django 5.1 on 2024-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('img_src', models.CharField(max_length=100, null=True)),
                ('trailer_link', models.CharField(max_length=100, null=True)),
                ('main_actor', models.CharField(max_length=100, null=True)),
                ('info', models.CharField(max_length=100, null=True)),
                ('release_date', models.DateField(max_length=100, null=True)),
                ('running_time', models.CharField(max_length=100, null=True)),
                ('screen_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='theater',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
    ]
