# Generated by Django 5.1 on 2024-09-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('screen', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('theater', models.CharField(max_length=100)),
            ],
        ),
    ]
