# Generated by Django 5.1 on 2024-10-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimeinfo',
            name='date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
