# Generated by Django 5.1 on 2024-09-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_movie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='theater',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='update_date',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='time',
            new_name='running_time',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='screen',
            new_name='screen_type',
        ),
        migrations.AddField(
            model_name='movie',
            name='main_actor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
