# Generated by Django 5.1 on 2024-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_movie_img_src_alter_movie_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
